# NUMPY practice session


In [1]:
# importing numpy
import numpy as np



## creating an array using numpy library

In [2]:
sabzi=np.array(["Gandi","Alwi","Muji","Gazri"])
sabzi


array(['Gandi', 'Alwi', 'Muji', 'Gazri'], dtype='<U5')

In [3]:
type(sabzi)

numpy.ndarray

In [4]:
len(sabzi)

4

In [5]:
prices=np.array([20,10,15,30])
prices


array([20, 10, 15, 30])

In [6]:
type(prices)

numpy.ndarray

In [7]:
len(prices)

4

####Indexing

In [8]:
sabzi[1]

'Alwi'

In [9]:
sabzi[0:]

array(['Gandi', 'Alwi', 'Muji', 'Gazri'], dtype='<U5')

In [10]:
sabzi[2:4]

array(['Muji', 'Gazri'], dtype='<U5')

In [11]:
prices[3]

30

In [12]:
#finding mean
prices.mean()

18.75

In [13]:
#An array of zeros
np.zeros(4,)

array([0., 0., 0., 0.])

In [14]:
np.ones(8)


array([1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 5.79044937e-321, 3.79442416e-321,
       1.65517906e-312])

In [16]:
# Using Arange
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
# specify
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [18]:
# specific intervel
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
#we can make table of any no as
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [20]:
#We can specify datatype of an arrayn

np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones(20,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Array functions

In [22]:
a=np.array([12,14,55,16,1.5,15.8,89.74,66.6])


In [23]:
a.sort()
a

array([ 1.5 , 12.  , 14.  , 15.8 , 16.  , 55.  , 66.6 , 89.74])

In [24]:
a.argmax()
a

array([ 1.5 , 12.  , 14.  , 15.8 , 16.  , 55.  , 66.6 , 89.74])

In [25]:
a.min()
a

array([ 1.5 , 12.  , 14.  , 15.8 , 16.  , 55.  , 66.6 , 89.74])

In [26]:
b=np.array([15,55,65,48,1.5,4.9,0.1,89.66,55,86,86.7])
b

array([15.  , 55.  , 65.  , 48.  ,  1.5 ,  4.9 ,  0.1 , 89.66, 55.  ,
       86.  , 86.7 ])

In [27]:
c=np.concatenate((a,b))
c

array([ 1.5 , 12.  , 14.  , 15.8 , 16.  , 55.  , 66.6 , 89.74, 15.  ,
       55.  , 65.  , 48.  ,  1.5 ,  4.9 ,  0.1 , 89.66, 55.  , 86.  ,
       86.7 ])

In [28]:
c.sort()
c


array([ 0.1 ,  1.5 ,  1.5 ,  4.9 , 12.  , 14.  , 15.  , 15.8 , 16.  ,
       48.  , 55.  , 55.  , 55.  , 65.  , 66.6 , 86.  , 86.7 , 89.66,
       89.74])

# 2 Dimensional Arrays

In [29]:
#formation of 2d Arrays
import numpy as np
a=np.array([[6,5,4],[12,11,10]])
a

array([[ 6,  5,  4],
       [12, 11, 10]])

In [30]:
#To find the no. of dimensional array a
a.ndim

2

In [31]:
b=np.array([[18,19,20],[17,16,15]])
b


array([[18, 19, 20],
       [17, 16, 15]])

In [32]:
#to find the no. of dimensions in array b
b.ndim

2

In [33]:
c=np.concatenate((a,b),axis=1)
#c.sort()
c

array([[ 6,  5,  4, 18, 19, 20],
       [12, 11, 10, 17, 16, 15]])

In [34]:
c.sort()
c

array([[ 4,  5,  6, 18, 19, 20],
       [10, 11, 12, 15, 16, 17]])

In [35]:
c=np.concatenate((a,b),axis=0)
c

array([[ 6,  5,  4],
       [12, 11, 10],
       [18, 19, 20],
       [17, 16, 15]])

In [36]:
c.sort()
c

array([[ 4,  5,  6],
       [10, 11, 12],
       [18, 19, 20],
       [15, 16, 17]])

# 3D Array

In [37]:
#importig library
import numpy as np
#example of 3d array
a=np.array([
    [[0,1,2,],      
    [4,5,6]],
            
     [[10,9,8],
     [13,11,12]],
            
     [[15,16,17],
    [18,19,20]]
])
a

array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[10,  9,  8],
        [13, 11, 12]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [38]:
# to find the no. of dimensions
a.ndim

3

In [39]:
a.sort()
a

array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [40]:
b=np.array([[5,6,7],[8,9,10],[0,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 0, 11, 12]])

In [41]:
b.ndim

2

In [42]:
#size (n0.of elements)
b.size

9

In [43]:
#length of an array in bytes
b.itemsize

4

In [44]:
b.dtype

dtype('int32')

In [45]:
a.size

18

In [46]:
a

array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]],

       [[15, 16, 17],
        [18, 19, 20]]])

In [47]:
#shape of the array
a.shape

(3, 2, 3)

In [48]:
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 0, 11, 12]])

In [49]:
b.shape

(3, 3)

In [50]:
###   <<<How to reshape an arraY>>>>>
import numpy as np
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
#Reshaping the array
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
#Another example of reshaping 
c=np.arange(4)
c

array([0, 1, 2, 3])

In [53]:
d=c.reshape(2,2)
# It will show error if you give wrong arguments
d

array([[0, 1],
       [2, 3]])

# Accessing specific elements, rows, columns etc  , INDEXING

In [54]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [55]:
#Get a specific element [r,c]  ##INDEXING##
a[0,5]   #0:first row ,5:fifth element (remember this is exclusive )


6

In [56]:
a[1,6]    ##1:2nd row ,6:sixth  element (remember this is exclusive )


14

In [57]:
# Also you can access elements by using negative indices 
a[0,-3]   #||ly u'can access elements from 2nd row as a[1,-3]


5

In [58]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [59]:
# Getting specific columns
a[:, 3]  #this is how cann you access any specific col.

array([ 4, 11])

In [60]:
a[:, 5]  #for 5th col.

array([ 6, 13])

In [61]:
#Getting a specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [63]:
#Getting a little more fancy[0(this means 1row),1(start index):5( end index):steps size]
a[0,0:4] #it will print 0-4 indices with inclusive(n-1)

array([1, 2, 3, 4])

In [64]:
 #using stepsize
a[1,0:6:2]#prints n-1 also uses same pro. for stepsize

array([ 8, 10, 12])

In [65]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [66]:
###<<<< CHANGING AN ELEMENT >>>>>from the array\
a[0,-2]=40000
a

array([[    1,     2,     3,     4,     5, 40000,     7],
       [    8,     9,    10,    11,    12,    13,    14]])

In [67]:
a[1,-4]=40000
a

array([[    1,     2,     3,     4,     5, 40000,     7],
       [    8,     9,    10, 40000,    12,    13,    14]])

In [68]:
# You can change a whole coln.
a[:,2]=5
a

array([[    1,     2,     5,     4,     5, 40000,     7],
       [    8,     9,     5, 40000,    12,    13,    14]])

In [69]:
#we can change both the rows As
a[:,:]= 6
a

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [70]:
a[:,:]=(0,1,2,3,4,5,6)
a

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [71]:
a[:,0]=[0,3] #changing first coln by 0,3
a

array([[0, 1, 2, 3, 4, 5, 6],
       [3, 1, 2, 3, 4, 5, 6]])

### INDEXING IN 3D,2D

In [72]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [73]:
#Getting specific elements
b.ndim

3

In [74]:
#Getting the no. 8
b[1,1,1]###  :- 1:2nd set,1:2nd row,1:2nd element

8

In [75]:
#print the no. 4 by using indexing?
b[0,1,1]

4

In [76]:
##change this element to 7?
b[0,1,1]=7
b

array([[[1, 2],
        [3, 7]],

       [[5, 6],
        [7, 8]]])

In [77]:
#Get the no. 5 from b
b[1,0,0]

5

In [78]:
#To get the different rows by different sets
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [79]:
#||ly getting 2nd row's of 1st and 2nd set
b[:,1,:]

array([[3, 7],
       [7, 8]])

In [80]:
#Changing these row's into different elements
b[:,1,:]=([98,66],[112,55])
b

array([[[  1,   2],
        [ 98,  66]],

       [[  5,   6],
        [112,  55]]])

# Initializing Different Types of arrays

In [81]:
#Making 2/3 of all 0's matrix
a=np.zeros((2,3),dtype="int32")   #two row's and 3 columns matrix
a

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
a.ndim

2

In [85]:
#3 dimensional using same method
b=np.zeros((2,3,3), dtype="int32")
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [86]:
b.ndim

3

In [88]:
#multidimensional matrix of any no.
        #Here you have to give two parameters As
np.full((2,2),55,dtype="float32")

array([[55., 55.],
       [55., 55.]], dtype=float32)

In [90]:
np.full((2,3),(88))

array([[88, 88, 88],
       [88, 88, 88]])

In [91]:
#there is an another method "full_like" to print the same 
# shape you have already used As:
np.full_like(a,5)

array([[5, 5, 5],
       [5, 5, 5]])

In [92]:
#we can make identity matrix as
#"identity matrix":"a square matrix in which all the
# elements of the principal
# diagonal are ones and all other elements are zeros."
np.identity(3) #this will print 3/3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
#Here is how can we repeat an array
arr=np.array((1,2,3))
r1=np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [97]:
#repeat on seperated axis
arr=np.array([[1,2,3]])
r2=np.repeat(arr,3,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [107]:
#making an matrix
                    [1,1,1,1,1]
                    [1,0,0,0,1]
                    [1,0,9,0,1]
                    [1,0,0,0,1]
                    [1,1,1,1,1]
matrix=np.ones((5,5))
matrix
mat=np.zeros((3,3))             
mat
mat[1,1]=9
mat 
matrix
matrix[1:4,1:4]=mat
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
# Methametics in numpy
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [110]:
#you can add any no. to elements of the array
a+2

array([3, 4, 5, 6])

In [111]:
#||ly you can subtract also
a-3

array([-2, -1,  0,  1])

In [119]:
# You can divide
a/2  #||ly you can apply other methametical operations
#np.sin(a)
#np.cos(a)
a

array([1, 2, 3, 4])

In [114]:
a

array([1, 2, 3, 4])

In [113]:
#Adding 2 arrays 
b=np.array([5,4,5,3])
b+a

array([6, 6, 8, 7])

### Linear Algebra